{
 "title": "Pizza Dashboard",
 "time": { "from": "2025-03-26T03:40:51.633Z", "to": "2025-03-26T04:10:51.633Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "activeUsers_total", "legendFormat": "Active Users" }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 0 },
   "targets": [
    { "expr": "authSuccess_total", "legendFormat": "Success" },
    { "expr": "authFailure_total", "legendFormat": "Failure" }
   ]
  },
  {
   "title": "HTTP requests /minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "targets": [
    { "expr": "requests_total", "legendFormat": "TOTAL" },
    { "expr": "getRequests_total", "legendFormat": "GET" },
    { "expr": "postRequests_total", "legendFormat": "POST" },
    { "expr": "putRequests_total", "legendFormat": "PUT" },
    { "expr": "delRequests_total", "legendFormat": "DELETE" }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 6 },
   "targets": [
    { "expr": "latency_milliseconds_total", "legendFormat": "Request Latency" }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "targets": [
    { "expr": "soldPizzas_total", "legendFormat": "Pizza's Sold" },
    { "expr": "pizzaFailures_total", "legendFormat": "Failures" }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "revenue_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 11 },
   "targets": [
    {
     "expr": "pizzaLatency_milliseconds_total",
     "legendFormat": "Latency"
    }
   ]
  }
 ]
}